# vim:ft=kitty

## name: Atelier Lakeside Dark
## author: Bram de Haan (https://github.com/atelierbram)
## license: MIT
## upstream: https://github.com/atelierbram/AtelierSchemes-kitty/blob/main/the>
## blurb: Cool colorscheme for the base color for Lakeside is blue, which mean>

#: URL underline color when hovering with mouse
url_color             #7DF9FF

#: kitty window border colors and terminal bell colors
active_border_color   #7DF9FF
inactive_border_color #292a2b
bell_border_color     #ff2c6d
visual_bell_color     none

#: OS Window titlebar colors
wayland_titlebar_color #1F1F20
macos_titlebar_color   #1F1F20

#: Tab bar colors
active_tab_foreground   #F0E0E6
active_tab_background   #1F1F20
inactive_tab_foreground #757575
inactive_tab_background #292a2b
tab_bar_background      #292a2b
tab_bar_margin_color    none

#: Colors for marks (marked text in the terminal)
mark1_foreground #1F1F20
mark1_background #7DF9FF
mark2_foreground #1F1F20
mark2_background #ff75b5
mark3_foreground #1F1F20
mark3_background #19f9d8

#: The basic colors
foreground            #F0E0E6
background            #1F1F20
selection_foreground  #1E1E1E
selection_background  #FF8C8C

#: Cursor colors
cursor                #7DF9FF
cursor_text_color     #292a2b

#: The basic 16 colors

#: black
color0 #000000
color8 #757575

#: red
color1 #ff2c6d
color9 #ff2c6d

#: green
color2  #19f9d8
color10 #19f9d8

#: yellow
color3  #ffb86c
color11 #ffcc95

#: blue
color4  #45a9f9
color12 #6fc1ff

#: magenta
color5  #ff75b5
color13 #ff9ac1

#: cyan
color6  #b084eb
color14 #bcaafe

#: white
color7  #cdcdcd
color15 #e6e6e6

