```conf
# Rosé Pine Enhanced

# Basic
foreground              #fff1f5
background              #181522
selection_foreground    #181522
selection_background    #9ccfd8

# Cursor
cursor                  #ffd27f
cursor_text_color       #181522

# Links
url_color               #9ccfd8

# Borders
active_border_color     #f4b8d3
inactive_border_color   #302b45
bell_border_color       #ff7aa2

# Tabs
active_tab_foreground   #181522
active_tab_background   #f4b8d3
inactive_tab_foreground #c8bfdc
inactive_tab_background #25203a
tab_bar_background      #14111d

# Marks
mark1_foreground #181522
mark1_background #f4b8d3
mark2_foreground #181522
mark2_background #9ccfd8
mark3_foreground #181522
mark3_background #ff7aa2

# black
color0  #2b2740
color8  #4d4768

# red (love)
color1  #ff7aa2
color9  #ff97b6

# green (pine)
color2  #5fae9b
color10 #9fded3

# yellow (gold)
color3  #ffd27f
color11 #ffe09c

# blue
color4  #8da7ff
color12 #adc1ff

# magenta (iris)
color5  #d4b4ff
color13 #e5caff

# cyan (foam)
color6  #9fded3
color14 #c6f5ed

# white
color7  #f5eefb
color15 #ffffff
```

