[main]
font=JetBrainsMono Nerd Font:size=13
dpi-aware=yes
anchor=center
lines=8
width=26
horizontal-pad=25
vertical-pad=20
inner-pad=10
radius=15

[colors]
# background=fff3edff
# text=42222aff
# match=f86b6bff
# selection=ffd9ccff
# selection-text=ff8c8cff
# border=ff8c8cff

background=181825ff
text=cad3f5ff
match=fe640bff
selection=81c8beff
selection-text=181825ff
border=ff8c8cff

[border]
width=4
radius=12
