#!/bin/bash

LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW_BIN="$(command -v eww)"

calendar() {
    if ! pidof eww >/dev/null; then
        "$EWW_BIN" daemon
        sleep 1
    fi

    if [ ! -f "$LOCK_FILE" ]; then
        touch "$LOCK_FILE"
        "$EWW_BIN" -c "$HOME/.config/eww/bar" open calendar
    else
        "$EWW_BIN" -c "$HOME/.config/eww/bar" close calendar
        rm -f "$LOCK_FILE"
    fi
}

case "$1" in
    launcher)
        "$HOME/.local/bin/launcher"
        ;;
    wifi)
        kitty -e nmtui
        ;;
    audio)
        pavucontrol
        ;;
    calendar)
        calendar
        ;;
esac

