# Paths
music_directory    "/Music/Music"
playlist_directory "~/.local/share/mpd/playlists"
db_file            "~/.config/mpd/Music/database"
pid_file           "~/.local/share/mpd/pid"
state_file         "~/.local/share/mpd/state"

# Network
bind_to_address    "127.0.0.1"
port               "6600"

# Audio Output
audio_output {
        type            "pipewire"
        name            "PipeWire Output"
}

