# ~/.config/foot/foot.ini

############################################################
# Font
############################################################

font=Sarasa Mono J:size=16
font-bold=Sarasa Mono J:size=16
font-italic=Sarasa Mono J:size=16
font-bold-italic=Sarasa Mono J:size=16

[main]
pad=10x10

############################################################
# Window
############################################################

[main]
term=xterm-256color
shell=/bin/bash
login-shell=yes

############################################################
# Cursor
############################################################

[cursor]
style=beam
blink=yes
beam-thickness=1

############################################################
# Mouse
############################################################

[mouse]
hide-when-typing=yes

[colors-dark]

alpha=0.90

foreground=e0def4
background=191724

selection-foreground=191724
selection-background=b49ad9

urls=89cfdc

# Regular
regular0=26233a
regular1=eb6f92
regular2=8db59f
regular3=f6c177
regular4=3e8fb0
regular5=c4a7e7
regular6=9ccfd8
regular7=e0def4

# Bright
bright0=6e6a86
bright1=e29ab5
bright2=a6d7c5
bright3=e6b267
bright4=74b7d8
bright5=d4b8f0
bright6=b5d8df
bright7=f6f3ff

############################################################
# CS
############################################################

[csd]
preferred=server

############################################################
# Bell
############################################################

[bell]
urgent=no
notify=no
visual=no

############################################################
# Scrollback
############################################################

[scrollback]
lines=100000

############################################################
# URL
############################################################

[url]
launch=xdg-open ${url}
osc8-underline=url-mode

############################################################
# Key Bindings
############################################################

[key-bindings]

scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down

clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

font-increase=Control+plus Control+equal
font-decrease=Control+minus
font-reset=Control+0

search-start=Control+Shift+f
show-urls-launch=Control+Shift+o

